### ISSUE TITLE
react-doc-gen-output.json is missing

### ISSUE THREAD

**Issue by morfarpeter** [DavidWells/react-autocomplete-cli#1]
When I try to run generate script, I get the error that the file react-doc-gen-output.json is missing.

React Doc Gen Finished. Build Tokens
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/Peter/Repositories/coastzone/node_modules/react-autocomplete-cli/react-doc-gen-output.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at generateCompletions (/Users/Peter/Repositories/coastzone/node_modules/react-autocomplete-cli/parse-docgen.js:14:33)
    at /Users/Peter/Repositories/coastzone/node_modules/react-autocomplete-cli/generate-completions.js:31:3
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)

I tried to generate an empty json file, but then my completions.json file was empty aswell. 

/Peter

**Comment by seishin4real** [comment]
I experience the same behavior.
I've even tried single-file method:
"generate": "rc-autocomplete --src 'src/components/App.js'"

also a file "react-docgen.js" openes in default text editor (sublime in this case)

**Comment by ganesharulanantham** [comment]
Any update on this ?

**Comment by SanthoshDhandapani** [comment]
It happens with windows system, kindly provide some update on this.

**Comment by jolaroux** [comment]
Any updates? Bueller? Bueller?

**Comment by jolaroux** [comment]
Alright if anyone still wants this info, I've been looking at his code and seeing what could go wrong. Some things are, he doesn't tell us that our component definitions have to follow the guidelines listed on this page: https://github.com/reactjs/react-docgen , because that's the tool he uses to analyze it. Something else I found is that even though it doesn't tell you anywhere, each .jsx file you use has to have only one component being exported in it... you can't have multiple. And the path name has to include the .jsx in it. Or if its a folder, the only files in it can be js/x files with only one component exported in each one. IF any of this doesn't help, what you can do is go to the node_modules/react-autocomplete-cli/ package, and change the bottom `exec` statement  and change it to 


exec(\`${docGenPath} ${componentsPath} -o ${tmpOutput}\`, {cwd: cwd}, function (error, stdout, stderr) {
  console.log('React Doc Gen Finished. Build Tokens')
  console.log("\n\n\n")
  console.log("ERROR")
  console.log(error)
  console.log("\n\n\n")
  console.log("STDOUT")
  console.log(stdout)
  console.log("\n\n\n")
  console.log("STDERR")
  console.log(stderr)
  console.log("\n\n\n")
  generateCompletions()
})


And this will output a more specific error as to what's going wrong. If there is any sort of error happening, it WON'T generate the `react-doc-gen-output.js` file that you're getting the error from.

Hope this helps!

**Comment by tibistibi** [comment]
i get this same problem more than a year later.... to bad  :-1: 

i have an ubuntu system

**Comment by ihorsahaidak** [comment]
I've an ubuntu 16.04 LTS and got the ERROR too (
any updates?

**Comment by DavidWells** [comment]
Hey there. I've abandoned this module.

The whole source code is pretty straight forward.

This file generates the completion json needed by the [atom autocomplete plus](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers) https://github.com/DavidWells/react-autocomplete-cli/blob/master/parse-docgen.js https://github.com/DavidWells/react-autocomplete-cli/blob/master/generate-completions.js 

Might need to tweak some stuff for ubuntu. 

I wrote this for my mac

**Comment by pralabhjain** [comment]
Run this command
"npm install react-toolbox"

and change .importjs.json with

{
  "lookupPaths": [
    "node_modules/react-toolbox/src/components/**/*.js",
    "app/src/components"
  ]
}
